(function(){
  "use strict";
  const PANEL_ID="gmAutoFetchStatusPanel", STYLE_ID="gmAutoFetchStatusStyle", REFRESH_MS=300000;
  const state={activity:null,scholarship:null,checkedAt:"",error:"",timer:null};
  const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;");
  const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
  const meta=p=>p&&typeof p.meta==="object"&&p.meta?p.meta:{};
  function list(p,k){if(Array.isArray(p))return p;if(Array.isArray(p?.[k]))return p[k];if(Array.isArray(p?.events))return p.events;if(Array.isArray(p?.scholarships))return p.scholarships;if(Array.isArray(p?.items))return p.items;return []}
  function fmt(v){if(!v)return"尚無紀錄";const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat("zh-TW",{timeZone:"Asia/Taipei",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).format(d)}
  function age(v){if(!v)return"無更新時間";const ms=Date.now()-new Date(v).getTime();if(!Number.isFinite(ms))return"時間格式待確認";const m=Math.max(0,Math.floor(ms/60000));if(m<60)return`${m} 分鐘前`;const h=Math.floor(m/60);return h<24?`${h} 小時前`:`${Math.floor(h/24)} 天前`}
  function taipei(){const o={};for(const x of new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Taipei",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date()))if(x.type!=="literal")o[x.type]=x.value;return{hour:+o.hour,minute:+o.minute}}
  function nextRun(){const p=taipei(),m=p.hour*60+p.minute;if(m<557)return"今天 09:17";if(m<647)return"今天 10:47（備援）";return"明天 09:17"}
  function sourceStats(m,kind){if(kind==="activity"){const t=num(m.sources??m.sourceCount??m.totalSources),h=num(m.healthySources??m.okSources??m.successSources??m.ok,t),f=num(m.failedSources??m.failed??m.failureSources,Math.max(0,t-h));return{total:t,healthy:h,failed:f}}const t=num(m.categories??m.sourceCount??m.totalSources),h=num(m.healthyCategories??m.okCategories??m.successCategories,t),f=num(m.failedCategories??m.failed??m.failureCategories,Math.max(0,t-h));return{total:t,healthy:h,failed:f}}
  function detailStats(m){const d=(m.eligibilityDetail&&typeof m.eligibilityDetail==="object")?m.eligibilityDetail:(m.detailEligibility&&typeof m.detailEligibility==="object"?m.detailEligibility:{});return{verified:num(d.detailVerified??d.verified),unverified:num(d.detailUnverified??d.unverified),fetched:num(d.detailFetched??d.fetched),reused:num(d.detailReused??d.reused),budgetExpired:num(d.detailBudgetExpired??d.budgetExpired),elapsed:num(d.detailElapsedSeconds??d.elapsedSeconds)}}
  function failures(m){const out=[];const add=v=>{if(v==null||v==="")return;if(typeof v==="string"){out.push(v);return}if(Array.isArray(v)){v.forEach(add);return}if(typeof v==="object"&&(v.ok===false||v.error||v.reason))out.push(`${v.name||v.id||v.sourceId||v.category||"來源"}：${v.error||v.reason||"失敗"}`)};[m.error,m.errors,m.failures,m.failedSources,m.report,m.sourceReport,m.categoryReport].forEach(add);return[...new Set(out.map(x=>String(x).trim()).filter(Boolean))].slice(0,3)}
  function normalize(payload,kind){const m=meta(payload);return{kind,count:list(payload,kind==="activity"?"events":"scholarships").length,updatedAt:m.updatedAt||m.fetchedAt||"",sources:sourceStats(m,kind),detail:kind==="scholarship"?detailStats(m):null,failures:failures(m)}}
  async function fetchJson(url){const sep=url.includes("?")?"&":"?",r=await fetch(url+sep+"health="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
  async function refresh(){state.checkedAt=new Date().toISOString();state.error="";const au=window.AppConfig?.data?.activities||"./data/activities.json",su=window.AppConfig?.data?.scholarships||"./data/scholarships.json";const[a,s]=await Promise.allSettled([fetchJson(au),fetchJson(su)]);if(a.status==="fulfilled")state.activity=normalize(a.value,"activity");else state.error="活動資料："+String(a.reason?.message||a.reason||"讀取失敗");if(s.status==="fulfilled")state.scholarship=normalize(s.value,"scholarship");else state.error+=(state.error?"；":"")+"獎學金資料："+String(s.reason?.message||s.reason||"讀取失敗");render();return snapshot()}
  const snapshot=()=>JSON.parse(JSON.stringify({activity:state.activity,scholarship:state.scholarship,checkedAt:state.checkedAt,error:state.error}));
  function sourceLine(x){if(!x)return"尚未讀取";const s=x.sources;return s.total?`${s.healthy}/${s.total} 正常${s.failed?` · 失敗 ${s.failed}`:""}`:"來源統計未提供"}
  function detailLine(x){const d=x?.detail;if(!d)return"";const p=[];if(d.verified||d.unverified)p.push(`資格驗證 ${d.verified} 成功 / ${d.unverified} 待重試`);if(d.fetched||d.reused)p.push(`本輪抓取 ${d.fetched} · 沿用 ${d.reused}`);if(d.budgetExpired)p.push(`逾時 ${d.budgetExpired}`);if(d.elapsed)p.push(`詳細資格 ${d.elapsed.toFixed(1)} 秒`);return p.join(" · ")||"資格詳細統計尚未提供"}
  function card(x,title){if(!x)return`<div class="gm-af-status-card warn"><div class="gm-af-status-title">${esc(title)}<span>待讀取</span></div><p>尚未取得資料狀態。</p></div>`;const warn=x.sources.failed>0||(x.kind==="scholarship"&&x.detail?.unverified>0),why=x.failures.length?`<div class="gm-af-status-reason">最近問題：${esc(x.failures.join("；"))}</div>`:"",det=x.kind==="scholarship"?`<div class="gm-af-status-detail">${esc(detailLine(x))}</div>`:"";return`<div class="gm-af-status-card ${warn?"warn":"ok"}"><div class="gm-af-status-title">${esc(title)}<span>${warn?"注意":"正常"}</span></div><div class="gm-af-status-grid"><span><small>資料量</small><b>${x.count}</b></span><span><small>來源</small><b>${esc(sourceLine(x))}</b></span></div><p>最後成功資料時間：${esc(fmt(x.updatedAt))}（${esc(age(x.updatedAt))}）</p>${det}${why}</div>`}
  function html(){const a=state.activity,s=state.scholarship,last=[a?.updatedAt,s?.updatedAt].filter(Boolean).sort().pop()||"",failed=(a?.sources.failed||0)+(s?.sources.failed||0),unv=s?.detail?.unverified||0,overall=state.error?"讀取異常":failed?"部分來源異常":unv?"資格待重試":"自動更新正常",cls=state.error||failed||unv?"warn":"ok";return`<section class="settings-section gm-af-status-section" id="${PANEL_ID}"><div class="settings-section-head"><div><h3>活動／獎學金自動更新健康紀錄</h3><p>直接讀取目前部署的正式資料；不會觸發 GitHub Actions，也不會修改本機資料。</p></div><span class="gm-af-status-pill ${cls}">${esc(overall)}</span></div><div class="gm-af-status-summary"><span><small>App</small><b>${esc(window.AppConfig?.version||"未知")}</b></span><span><small>最近資料更新</small><b>${esc(last?fmt(last):"尚無")}</b></span><span><small>下次預計排程</small><b>${esc(nextRun())}</b></span><span><small>每日排程</small><b>09:17／10:47</b></span></div><div class="gm-af-status-cards">${card(a,"活動雷達")}${card(s,"獎學金")}</div>${state.error?`<div class="gm-af-status-error">${esc(state.error)}</div>`:""}<div class="gm-af-status-actions"><button class="btn" type="button" onclick="GoalManagerAutoFetchStatus.refresh()">重新讀取狀態</button><span>本機檢查：${esc(fmt(state.checkedAt))} · Asia/Taipei</span></div></section>`}
  function styles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement("style");s.id=STYLE_ID;s.textContent=`.gm-af-status-section{margin-top:16px}.gm-af-status-pill{display:inline-flex;padding:5px 9px;border-radius:999px;font-size:12px;font-weight:800;white-space:nowrap}.gm-af-status-pill.ok{background:#e9f7f0;color:#126c50}.gm-af-status-pill.warn{background:#fff4d8;color:#8a6500}.gm-af-status-summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:12px 0}.gm-af-status-summary span{display:flex;flex-direction:column;gap:3px;padding:10px;border-radius:13px;background:rgba(15,86,65,.055)}.gm-af-status-summary small{font-size:11px;color:#74807c}.gm-af-status-summary b{font-size:13px;line-height:1.4}.gm-af-status-cards{display:grid;gap:9px}.gm-af-status-card{padding:12px;border:1px solid rgba(15,86,65,.13);border-radius:15px}.gm-af-status-card.warn{border-color:rgba(172,125,0,.28);background:rgba(255,246,220,.45)}.gm-af-status-title{display:flex;align-items:center;justify-content:space-between;gap:10px;font-weight:800}.gm-af-status-title span{font-size:11px;padding:3px 7px;border-radius:999px;background:#eef6f2;color:#126c50}.gm-af-status-card.warn .gm-af-status-title span{background:#fff0bf;color:#8a6500}.gm-af-status-grid{display:grid;grid-template-columns:88px 1fr;gap:8px;margin:10px 0}.gm-af-status-grid span{display:flex;flex-direction:column;gap:2px}.gm-af-status-grid small{font-size:10px;color:#7b8783}.gm-af-status-grid b{font-size:13px}.gm-af-status-card p,.gm-af-status-detail,.gm-af-status-reason{margin:6px 0 0;font-size:11px;line-height:1.55;color:#6d7975}.gm-af-status-reason,.gm-af-status-error{color:#8a6500}.gm-af-status-error{margin-top:9px;padding:9px;border-radius:12px;background:#fff4d8;font-size:11px}.gm-af-status-actions{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-top:11px;font-size:11px;color:#7b8783}html.app-dark .gm-af-status-summary span{background:#17211e}html.app-dark .gm-af-status-card{border-color:#34433e}html.app-dark .gm-af-status-card.warn{background:#2a2415}`;document.head.appendChild(s)}
  function render(){styles();const body=document.getElementById("settingsBody");if(!body)return;document.getElementById(PANEL_ID)?.remove();const life=document.getElementById("gmCatalogLifecyclePanel"),health=document.getElementById("gmAutoFetchHealth");if(life)life.insertAdjacentHTML("afterend",html());else if(health)health.insertAdjacentHTML("afterend",html());else body.insertAdjacentHTML("beforeend",html())}
  function hook(){if(typeof window.renderSettings!=="function"||window.renderSettings.__gmAutoFetchStatusWrapped)return;const original=window.renderSettings,wrapped=function(){const out=original.apply(this,arguments);setTimeout(render,0);return out};wrapped.__gmAutoFetchStatusWrapped=true;window.renderSettings=wrapped}
  function boot(){styles();hook();refresh().catch(e=>{state.error=String(e?.message||e);render()});window.addEventListener("online",()=>refresh().catch(()=>{}));document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&Date.now()-new Date(state.checkedAt||0).getTime()>REFRESH_MS)refresh().catch(()=>{})});state.timer=setInterval(()=>refresh().catch(()=>{}),REFRESH_MS)}
  window.GoalManagerAutoFetchStatus=Object.freeze({refresh,status:snapshot,render});
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();
