const assert=require('assert');
const AnalyticsPage=require('../../js/ui/pages/analytics-page.js');
assert.strictEqual(AnalyticsPage.formatMinutes(0),'0m');assert.strictEqual(AnalyticsPage.formatMinutes(90),'1h 30m');
const recent=AnalyticsPage.recentActualLogsHTML([{id:'l1',taskId:'t1',name:'行政法',time:'2026-10-03T10:30:00+08:00',minutes:45}],{esc:x=>String(x),getTask:()=>null,isOtherStudyLog:()=>false});assert(recent.includes('行政法'));assert(recent.includes('45 分'));assert(recent.includes('查看全部紀錄'));
const review=AnalyticsPage.weeklyReviewHTML([{t:{id:'t1',name:'行政法'},w:{target:120,actual:60},shortfall:60,review:{reason:'課業負荷'}}],{date:'2026-10-03',reasons:['課業負荷','時間不足'],esc:x=>String(x),calc:()=>30});assert(review.includes('行政法'));assert(review.includes('課業負荷'));assert(review.includes('30%'));
const nodes={leafDone:{textContent:'',style:{}},avg:{textContent:'',style:{}},weekCreditedKpi:{textContent:'',style:{}},logsN:{textContent:'',style:{}},statsWeekRatio:{textContent:'',style:{}},statsWeekBar:{textContent:'',style:{}},statsActual:{textContent:'',style:{}},statsCredited:{textContent:'',style:{}},statsOverrun:{textContent:'',style:{}},statsOtherStudy:{textContent:'',style:{}},statsTotalStudy:{textContent:'',style:{}},statsTarget:{textContent:'',style:{}},statsRemaining:{textContent:'',style:{}},domains:{innerHTML:'',style:{},textContent:''},progressDistribution:{innerHTML:'',style:{},textContent:''}};
AnalyticsPage.renderStats({document:{getElementById:id=>nodes[id]||null},leaves:[],done:0,avg:0,week:{ratio:53,goalActualMinutes:582,creditedGoalMinutes:549,overrunGoalMinutes:33,otherStudyMinutes:59,totalStudyMinutes:641,target:1030,remaining:481},directionRows:[{rootId:'r1',name:'台大及政大轉學考',actual:500,credited:470,overrun:30,target:930,remaining:460,ratio:51}],actualLogCount:58,esc:x=>String(x),calc:()=>0});
assert.strictEqual(nodes.weekCreditedKpi.textContent,'549');assert.strictEqual(nodes.statsWeekRatio.textContent,'53%');assert(nodes.domains.innerHTML.includes('實際 500 分'));assert(nodes.domains.innerHTML.includes('有效 470 分'));assert(nodes.domains.innerHTML.includes('超時 30 分'));assert(nodes.domains.innerHTML.includes('目標 930 分'));assert(!nodes.domains.innerHTML.includes('計畫實際'));
console.log('OK: AnalyticsPage weekly study and direction rendering');
