'use strict';
const APP_VERSION='2.0.0-github';
const CATEGORIES=[['食','🍜','餐飲'],['衣','👕','服飾'],['住','💡','水電'],['行','🚆','交通'],['育','📚','學習'],['樂','🎮','娛樂']];
const main=document.getElementById('appMain'),dialog=document.getElementById('amountDialog'),amountTitle=document.getElementById('amountTitle'),amountInput=document.getElementById('amountInput'),saveAmountButton=document.getElementById('saveAmount');
let route='entry',selectedCategory=null,showId=false;
const nowIso=()=>new Date().toISOString();
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const money=v=>new Intl.NumberFormat('zh-TW',{maximumFractionDigits:0}).format(Math.round(Number(v)||0));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const load=(k,f)=>{try{const r=localStorage.getItem(k);return r?JSON.parse(r):f}catch{return f}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));

function makeLedgerId(){const b=new Uint8Array(16);crypto.getRandomValues(b);return'lg-'+Array.from(b,x=>x.toString(16).padStart(2,'0')).join('')}
function ledgerId(){let id=localStorage.getItem('lazyLedgerId')||'';if(/^lg-[a-f0-9]{32}$/.test(id))return id;id=makeLedgerId();localStorage.setItem('lazyLedgerId',id);return id}
const cacheKey=(id=ledgerId())=>`lazyLedgerCache:${id}`;
function defaultConfig(){return{ledgerId:ledgerId(),allowanceInitial:8000,allowanceRemaining:0,allowanceCycle:0,allowanceActive:false,allowanceStartedAt:'',periodStartDay:1,recurring:[],updatedAt:nowIso()}}
function normalizeState(raw){
 const base=(raw&&typeof raw==='object')?JSON.parse(JSON.stringify(raw)):{};
 const out={config:{...defaultConfig(),...(base.config||{})},transactions:Array.isArray(base.transactions)?base.transactions:[]};
 out.config.recurring=Array.isArray(out.config.recurring)?out.config.recurring:[];
 out.transactions=out.transactions.filter(x=>x&&CATEGORIES.some(c=>c[0]===x.category)&&Number(x.amount)>0).map((x,i)=>{
   const amount=Math.round(Number(x.amount)||0),allowance=Math.max(0,Math.min(amount,Math.round(Number(x.allowanceAmount)||0)));
   return {...x,id:String(x.id||`imported-${Date.now()}-${i}`),clientId:String(x.clientId||x.id||`imported-client-${Date.now()}-${i}`),timestamp:String(x.timestamp||nowIso()),category:x.category,amount,allowanceAmount:allowance,selfPaidAmount:amount-allowance,source:x.source==='recurring'?'recurring':'manual',allowanceCycle:Math.max(0,Math.round(Number(x.allowanceCycle)||0)),createdAt:String(x.createdAt||x.timestamp||nowIso())};
 });
 return out;
}
let state=normalizeState(load(cacheKey(),{config:defaultConfig(),transactions:[]}));

function persist(){state.config.updatedAt=nowIso();save(cacheKey(),state)}
function snapshot(label){const rows=load('lazyLedgerGithubSnapshots',[]);rows.push({label,at:nowIso(),ledgerId:ledgerId(),state:JSON.parse(JSON.stringify(state))});save('lazyLedgerGithubSnapshots',rows.slice(-8))}
function eligible(c){return c==='食'||c==='住'}
function activeAllowance(){return state.config.allowanceActive!==false}
function recompute(){const active=activeAllowance(),initial=Number(state.config.allowanceInitial)||8000,cycle=Number(state.config.allowanceCycle)||0,used=active?state.transactions.filter(x=>Number(x.allowanceCycle)===cycle).reduce((s,x)=>s+Math.max(0,Math.min(Number(x.amount)||0,Number(x.allowanceAmount)||0)),0):0;state.config.allowanceRemaining=active?Math.max(0,initial-used):0}
function toast(m){const h=document.getElementById('toastHost'),e=document.createElement('div');e.className='toast';e.textContent=m;h.appendChild(e);setTimeout(()=>e.remove(),2200)}
function periodBounds(ref=new Date()){const day=Math.max(1,Math.min(28,Number(state.config.periodStartDay)||1));let y=ref.getFullYear(),m=ref.getMonth();if(ref.getDate()<day)m--;const start=new Date(y,m,day),end=new Date(start.getFullYear(),start.getMonth()+1,day);return{start,end}}
function periodKey(d){const s=periodBounds(d).start;return`${s.getFullYear()}-${String(s.getMonth()+1).padStart(2,'0')}-${String(s.getDate()).padStart(2,'0')}`}
function periodLabel(s,e){const x=new Date(e.getTime()-86400000);return`${s.getMonth()+1}/${s.getDate()}–${x.getMonth()+1}/${x.getDate()}`}
function currentRows(){const {start,end}=periodBounds();return state.transactions.filter(x=>{const t=Date.parse(x.timestamp);return t>=start.getTime()&&t<end.getTime()})}
function totals(rows){const by=Object.fromEntries(CATEGORIES.map(x=>[x[0],0]));let total=0,allowance=0,self=0;rows.forEach(x=>{by[x.category]+=x.amount;total+=x.amount;allowance+=x.allowanceAmount;self+=x.selfPaidAmount});return{by,total,allowance,self}}
function latest(){return[...state.transactions].sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp))[0]}
function applyRecurring(){
 const d=localDate(),ym=d.slice(0,7),day=Number(d.slice(8)),rules=state.config.recurring||[];
 for(const r of rules){if(r.enabled===false||day<Number(r.day)||r.lastAppliedKey===ym)continue;const key=`${r.id}:${ym}`;if(!state.transactions.some(x=>x.recurringKey===key)){const amount=Math.round(Number(r.amount)||0),cat=r.category;if(amount>0&&CATEGORIES.some(x=>x[0]===cat)){const allow=activeAllowance()&&eligible(cat)?Math.min(state.config.allowanceRemaining,amount):0;state.transactions.unshift({id:`rec-${r.id}-${ym}`,clientId:`rec-${r.id}-${ym}`,timestamp:`${ym}-${String(r.day).padStart(2,'0')}T12:00:00+08:00`,category:cat,amount,allowanceAmount:allow,selfPaidAmount:amount-allow,source:'recurring',recurringKey:key,allowanceCycle:state.config.allowanceCycle,createdAt:nowIso()});recompute()}}r.lastAppliedKey=ym}
 persist()
}
function txRow(x){const src=x.allowanceAmount>0&&x.selfPaidAmount>0?`生活 ${money(x.allowanceAmount)} · 自費 ${money(x.selfPaidAmount)}`:x.allowanceAmount>0?`生活費 ${money(x.allowanceAmount)}`:`自費 ${money(x.selfPaidAmount)}`;const time=new Date(x.timestamp).toLocaleString('zh-TW',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});return`<div class="recent-row"><div><span class="recent-cat">${x.category}</span><div><strong>${money(x.amount)}</strong><small>${time}${x.source==='recurring'?' · 自動':''}</small></div></div><div class="split-mini">${src}</div><button class="delete-tx" data-del="${esc(x.id)}">×</button></div>`}
function grouped(rows){const m=new Map();[...rows].sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp)).forEach(x=>{const k=x.timestamp.slice(0,10),a=m.get(k)||[];a.push(x);m.set(k,a)});return[...m.entries()].map(([k,a])=>`<section class="records-day"><div class="records-day-head"><span>${k}</span><b>${a.length} 筆 · ${money(totals(a).total)}</b></div>${a.map(txRow).join('')}</section>`).join('')}
function entryPage(){const rows=currentRows(),sum=totals(rows),{start,end}=periodBounds(),l=latest();return`<section class="summary-card"><div><p>本期已花</p><strong>NT$ ${money(sum.total)}</strong><small>${periodLabel(start,end)}</small></div><div class="mini-grid"><div><span>生活費</span><b>${activeAllowance()?money(state.config.allowanceRemaining):'尚未開始'}</b></div><div><span>本期自費</span><b>${money(sum.self)}</b></div></div>${activeAllowance()?'':'<button id="receiveAllowance" class="primary wide">我已收到第一筆 $8,000</button>'}</section><div class="section-head"><div><p class="eyebrow">ONE TAP</p><h2>花在哪裡？</h2></div><span class="badge">本機保存</span></div><section class="category-grid">${CATEGORIES.map(([k,i,s])=>`<button class="category-btn" data-cat="${k}"><span class="cat-icon">${i}</span><strong>${k}</strong><small>${s}</small></button>`).join('')}</section><div class="quick-row"><button id="undoLast" class="secondary wide" ${l?'':'disabled'}>↶ 撤銷上一筆${l?` · ${l.category} ${money(l.amount)}`:''}</button></div><div class="section-head compact"><div><h3>最近紀錄</h3></div><span class="badge">本期 ${rows.length} 筆</span></div><section class="recent-list">${rows.length?[...rows].sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp)).slice(0,3).map(txRow).join(''):'<div class="empty-card">本期還沒有支出。</div>'}</section>${rows.length>3?`<details class="all-records"><summary><span>查看本期全部紀錄</span><b>${rows.length} 筆</b></summary><div class="all-records-scroll">${grouped(rows)}</div></details>`:''}`}
function periodPage(){const rows=currentRows(),sum=totals(rows),sorted=CATEGORIES.map(x=>({k:x[0],i:x[1],amount:sum.by[x[0]]})).sort((a,b)=>b.amount-a.amount),max=Math.max(1,...sorted.map(x=>x.amount)),{start,end}=periodBounds();return`<section class="hero"><p class="eyebrow">CURRENT PERIOD</p><h2>NT$ ${money(sum.total)}</h2><p>${periodLabel(start,end)}</p></section><div class="section-head"><h3>六類支出排行</h3></div><section class="bar-card">${sorted.map(x=>`<div class="bar-row"><div class="bar-label"><span>${x.i} ${x.k}</span><b>${money(x.amount)}</b></div><div class="bar-track"><i style="width:${Math.round(x.amount/max*100)}%"></i></div><small>${sum.total?Math.round(x.amount/sum.total*100):0}%</small></div>`).join('')}</section><div class="section-head"><h3>錢從哪裡出</h3></div><section class="source-grid"><div class="card"><span>生活費支出</span><strong>${money(sum.allowance)}</strong><small>食、住（水電）</small></div><div class="card"><span>自費支出</span><strong>${money(sum.self)}</strong><small>其他支出或生活費不足</small></div></section>`}
function historyPage(){const g=new Map();state.transactions.forEach(x=>{const k=periodKey(new Date(x.timestamp)),a=g.get(k)||[];a.push(x);g.set(k,a)});const keys=[...g.keys()].sort().reverse().slice(0,12);return`<section class="hero"><p class="eyebrow">HISTORY</p><h2>歷史檔案庫</h2><p>依起算日自動分期。</p></section><section class="history-list">${keys.length?keys.map(k=>{const rows=g.get(k),sum=totals(rows),s=new Date(`${k}T00:00:00`),e=new Date(s.getFullYear(),s.getMonth()+1,state.config.periodStartDay||1);return`<details class="history-card"><summary><div><small>${periodLabel(s,e)}</small><strong>${money(sum.total)}</strong></div><span>${rows.length} 筆</span></summary><div class="history-body">${CATEGORIES.map(x=>`<div><span>${x[0]}</span><b>${money(sum.by[x[0]])}</b></div>`).join('')}<hr><div><span>生活費</span><b>${money(sum.allowance)}</b></div><div><span>自費</span><b>${money(sum.self)}</b></div></div></details>`}).join(''):'<div class="empty-card">尚無歷史資料。</div>'}</section>`}
function backupObject(){const keys={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('lazyLedger'))keys[k]=localStorage.getItem(k)}return{schema:'lazy-ledger-github-backup-v1',version:APP_VERSION,exportedAt:nowIso(),keys}}
function downloadBackup(){const blob=new Blob([JSON.stringify(backupObject(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`lazy-ledger-backup-${localDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function parseBackupObject(obj){
 if(obj&&obj.keys&&typeof obj.keys==='object')return obj.keys;
 if(obj&&obj.config&&Array.isArray(obj.transactions)){
   const id=String(obj.config.ledgerId||ledgerId());
   return{lazyLedgerId:id,[`lazyLedgerCache:${id}`]:JSON.stringify(obj)};
 }
 throw new Error('備份格式不符');
}
function importBackup(file){const r=new FileReader();r.onload=()=>{try{const obj=JSON.parse(String(r.result||'')),keys=parseBackupObject(obj);let idRaw=keys.lazyLedgerId;let id='';try{id=JSON.parse(idRaw)}catch{id=String(idRaw||'').replace(/^"|"$/g,'')}if(!/^lg-[a-f0-9]{32}$/.test(id))throw new Error('帳本識別碼不正確');const primary=`lazyLedgerCache:${id}`,raw=keys[primary];if(!raw)throw new Error('找不到主要帳本交易資料');const probe=normalizeState(typeof raw==='string'?JSON.parse(raw):raw);for(const x of probe.transactions){if(x.allowanceAmount+x.selfPaidAmount!==x.amount)throw new Error('交易資金拆分不一致')}snapshot('before-import');Object.entries(keys).forEach(([k,v])=>{if(k.startsWith('lazyLedger'))localStorage.setItem(k,typeof v==='string'?v:JSON.stringify(v))});localStorage.setItem('lazyLedgerId',id);state=normalizeState(load(primary,probe));recompute();persist();toast(`匯入完成 · ${state.transactions.length} 筆`);render()}catch(e){console.error(e);toast(`匯入失敗：${e.message||e}`)}};r.readAsText(file)}
function settingsPage(){return`<div class="section-head"><h2>設定</h2><span class="badge">v${APP_VERSION}</span></div><section class="card settings-card"><div class="setting-title"><div><span class="eyebrow">ALLOWANCE</span><h3>${activeAllowance()?`生活費第 ${state.config.allowanceCycle} 期`:'生活費尚未開始'}</h3></div><strong>${activeAllowance()?`${money(state.config.allowanceRemaining)} / 8,000`:'尚未起算'}</strong></div><p class="muted">只有食與住（水電）會扣生活費；付款當下決定資金來源，不回溯改列。</p>${!activeAllowance()?'<button id="receiveAllowance" class="primary wide">我已收到第一筆 $8,000</button>':state.config.allowanceRemaining<=0?'<button id="receiveAllowance" class="primary wide">已收到下一筆 $8,000</button>':'<button class="secondary wide" disabled>生活費用完後才可領下一筆</button>'}</section><section class="card settings-card"><h3>記帳週期</h3><label class="setting"><span>每月起算日</span><input id="periodStartDay" type="number" min="1" max="28" value="${state.config.periodStartDay}"></label><button id="savePeriod" class="secondary wide">儲存起算日</button></section><section class="card settings-card"><div class="setting-title"><div><span class="eyebrow">AUTOMATION</span><h3>固定花費</h3></div><span class="badge">${state.config.recurring.length} 項</span></div><div class="rule-list">${state.config.recurring.length?state.config.recurring.map(r=>`<div class="rule-row"><div><strong>${esc(r.name)}</strong><small>${r.category} · 每月 ${r.day} 日 · ${money(r.amount)}</small></div><button class="ghost danger" data-rule-del="${esc(r.id)}">刪除</button></div>`).join(''):'<p class="muted">沒有固定支出。</p>'}</div><form id="ruleForm" class="rule-form"><input id="ruleName" placeholder="名稱，例如：電費"><div class="two-col"><select id="ruleCategory">${CATEGORIES.map(x=>`<option>${x[0]}</option>`).join('')}</select><input id="ruleAmount" type="number" min="1" placeholder="金額"></div><div class="two-col"><input id="ruleDay" type="number" min="1" max="28" value="1"><button class="primary" type="submit">新增固定花費</button></div></form></section><section class="card settings-card migration-card"><div class="setting-title"><div><span class="eyebrow">MIGRATION SAFE</span><h3>完整備份／匯入</h3></div><span class="badge">本機</span></div><p class="muted">匯出會包含目前帳本、舊帳本候選、草稿與待處理資料。匯入前會先在本機建立安全快照。</p><div class="actions"><button id="exportBackup" class="primary">匯出完整備份</button></div><input id="importBackupFile" class="file-input" type="file" accept=".json,application/json"><button id="importBackup" class="secondary wide">匯入 AppDeploy／GitHub 備份</button></section><section class="card settings-card"><div class="setting-title"><div><span class="eyebrow">LOCAL ID</span><h3>帳本識別碼</h3></div></div><p class="muted">${showId?esc(ledgerId()):'lg-••••••••••••••••••••••••••••••••'}</p><button id="toggleId" class="ghost">${showId?'隱藏':'顯示'}</button></section>`}
function render(){main.innerHTML=route==='entry'?entryPage():route==='period'?periodPage():route==='history'?historyPage():settingsPage();bind()}
function bind(){
 document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>openAmount(b.dataset.cat));
 document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteTx(b.dataset.del));
 document.querySelector('#undoLast')?.addEventListener('click',undoLast);
 document.querySelector('#receiveAllowance')?.addEventListener('click',receiveAllowance);
 document.querySelector('#savePeriod')?.addEventListener('click',()=>{state.config.periodStartDay=Math.max(1,Math.min(28,Number(document.querySelector('#periodStartDay').value)||1));persist();render();toast('起算日已儲存')});
 document.querySelector('#ruleForm')?.addEventListener('submit',e=>{e.preventDefault();const name=document.querySelector('#ruleName').value.trim(),cat=document.querySelector('#ruleCategory').value,amount=Math.round(Number(document.querySelector('#ruleAmount').value)),day=Math.round(Number(document.querySelector('#ruleDay').value));if(!name||amount<=0||day<1||day>28)return toast('請填有效固定支出');state.config.recurring.push({id:`r-${Date.now()}-${Math.random().toString(36).slice(2)}`,name,category:cat,amount,day,enabled:true,createdAt:nowIso()});persist();render();toast('已新增固定支出')});
 document.querySelectorAll('[data-rule-del]').forEach(b=>b.onclick=()=>{state.config.recurring=state.config.recurring.filter(x=>x.id!==b.dataset.ruleDel);persist();render()});
 document.querySelector('#exportBackup')?.addEventListener('click',downloadBackup);
 document.querySelector('#importBackup')?.addEventListener('click',()=>{const f=document.querySelector('#importBackupFile').files?.[0];if(!f)return toast('請先選擇備份 JSON');importBackup(f)});
 document.querySelector('#toggleId')?.addEventListener('click',()=>{showId=!showId;render()})
}
function openAmount(cat){selectedCategory=cat;amountTitle.textContent=`${cat}${cat==='住'?' · 水電':''}`;amountInput.value='';saveAmountButton.textContent=`記下 · ${cat}`;dialog.showModal();setTimeout(()=>amountInput.focus(),80)}
function addExpense(){if(!selectedCategory)return;const amount=Math.round(Number(amountInput.value));if(amount<=0)return toast('請輸入金額');const allow=activeAllowance()&&eligible(selectedCategory)?Math.min(state.config.allowanceRemaining,amount):0;const id=`local-${Date.now()}-${Math.random().toString(36).slice(2)}`;state.transactions.unshift({id,clientId:id,timestamp:nowIso(),category:selectedCategory,amount,allowanceAmount:allow,selfPaidAmount:amount-allow,source:'manual',allowanceCycle:state.config.allowanceCycle,createdAt:nowIso()});recompute();persist();dialog.close();selectedCategory=null;render();toast(`已記錄 ${money(amount)}`)}
function deleteTx(id){snapshot('before-delete');state.transactions=state.transactions.filter(x=>x.id!==id);recompute();persist();render();toast('已刪除')}
function undoLast(){const x=latest();if(!x)return;deleteTx(x.id)}
function receiveAllowance(){const first=!activeAllowance();if(!first&&state.config.allowanceRemaining>0)return toast('目前生活費尚未用完');state.config.allowanceActive=true;state.config.allowanceCycle=first?1:(Number(state.config.allowanceCycle)||0)+1;state.config.allowanceRemaining=Number(state.config.allowanceInitial)||8000;state.config.allowanceStartedAt=nowIso();persist();render();toast(first?'第 1 期生活費已開始':'已開始下一期生活費')}
saveAmountButton.onclick=addExpense;amountInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addExpense()}});
dialog.addEventListener('close',()=>{selectedCategory=null;amountInput.value=''});
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{route=b.dataset.route;document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x===b));render()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
recompute();persist();applyRecurring();render();
